#!/bin/bash

if [ -z "$1" ]
then
    dic="$(xclip -selection primary -o)"
else
    dic=$1
fi

if [ ${#dic} -eq 1 ]; then
    notify-send -t 8000 "$(grep $dic ~/Documents/Programs/Linux/Anki/Kodansha_Kanji_dictionary.txt)"

else
    check="$(echo "$(sdcv -e "$dic")" | awk '{ print $1" "$2 }')"
    if [[ "$check" = "Nothing similar" ]]
    then
        dunstify "Searching Jisho..." & jisho-cli -c never "$dic">/tmp/dic
        dunstify -t 12000 "$(cat /tmp/dic)" && def_sound "$dic"
        cat /tmp/dic | xclip -i -selection clipboard
    else
        sdcv -e "$dic">/tmp/dic
        dunstify -t 12000 "$(cat /tmp/dic)" && def_sound "$dic"
        cat /tmp/dic | xclip -i -selection clipboard
    fi
fi

