#!/bin/bash
input="$1"
cd /home/linuxs/Documents/Programs/Linux/Dictionaries/japanese_sound
find . -type f \( -name "$input.yomi*" -o -name "$input-*_male*" \) -print -quit | xargs mpv --really-quiet

